name: Publish NPM Package

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a version tag is pushed

jobs:
  validate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Validate Tag and Package Version
        run: |
          # Extract tag version (removing the 'v' prefix)
          TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')

          # Get package.json version
          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          # Compare versions
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
